version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk21
  pre-build:
    commands:
      - mvn install
  build:
    commands:
      - mvn package
artifacts:
  files:
    - 'target/Bierkasse-0.0.1-SNAPSHOT.jar'
    - 'Dockerfile'
    - 'src/main/resources/*'